# Generated by Django 5.1.4 on 2024-12-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_mun'),
    ]

    operations = [
        migrations.AddField(
            model_name='mun',
            name='description',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
