# Generated by Django 5.1.4 on 2024-12-15 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_mun_registration_mun_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='user',
            new_name='user_id',
        ),
    ]
