# Generated by Django 5.1.4 on 2024-12-15 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_user_registration_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='mun_id',
            new_name='mun',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='user_id',
            new_name='user',
        ),
    ]
