# Generated by Django 5.1.4 on 2024-12-15 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_payment_registration_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='mun',
            new_name='mun_id',
        ),
    ]
