# Generated by Django 5.1.4 on 2024-12-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_mun_id_registration_mun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mun',
            name='description',
            field=models.TextField(),
        ),
    ]
